environment:
  name: prod
  project: cdf-bootcamp-71-prod # ex. cdf-bootcamp-01-test
  validation-type: prod # prod, staging, dev, test, qa
  selected:
    - modules/bootcamp/data_foundation
    - modules/bootcamp/ice_cream_api
    - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space

      data_foundation:
        data_developer_source_id: db433667-5fd8-4eb3-ab48-6e2cc788ad34

      ice_cream_api:
        icapi_extractors_source_id: 753abeb5-200c-4f5d-a201-3a93f632a519

        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${IDP_CLIENT_ID}
        icapi_trigger_client_secret: ${IDP_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}

      use_cases:
        oee:
          data_pipeline_oee_source_id: 5b2b9774-d6a6-46e7-85e6-ab1db27d4635

          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}
